dbschema -d logix -t gm_polimetri gm_polimetri.sql
dbschema -d logix -t doc_desc_polimetri doc_desc_polimetri.sql
dbschema -d logix -t est_hist_polimetri est_hist_polimetri.sql
dbschema -d logix -t par_vdp_polimetri par_vdp_polimetri.sql
dbschema -d logix -t movto_ega_polimetri movto_ega_polimetri.sql
dbschema -d logix -t maq_ega_polimetr maq_ega_polimetr.sql
dbschema -d logix -t est_oper_polimetri est_oper_polimetri.sql
dbschema -d logix -t port_des_polimetri port_des_polimetri.sql
dbschema -d logix -t evento_polimetri evento_polimetri.sql
dbschema -d logix -t man_apont_hist_454 man_apont_hist_454.sql
dbschema -d logix -t man_apont_454 man_apont_454.sql
dbschema -d logix -t de_para_embal de_para_embal.sql
dbschema -d logix -t desc_dup_polimetri desc_dup_polimetri.sql
dbschema -d logix -t cta_cont_polimetri cta_cont_polimetri.sql
dbschema -d logix -t port_polimetri port_polimetri.sql
dbschema -d logix -t maq_ega_man912 maq_ega_man912.sql
dbschema -d logix -t mov_ega_man912 mov_ega_man912.sql
dbschema -d logix -t peca_geme_man912 peca_geme_man912.sql
dbschema -d logix -t ordens_export_912 ordens_export_912.sql
dbschema -d logix -t oper_ega_man912 oper_ega_man912.sql
dbschema -d logix -t man_apont_hist_454 man_apont_hist_454.sql
dbschema -d logix -t pct_ajust_man912 pct_ajust_man912.sql
dbschema -d logix -t par_ega_logix_912 par_ega_logix_912.sql
dbschema -d logix -t apont_ega_man912 apont_ega_man912.sql
dbschema -d logix -t man_apont_454 man_apont_454.sql
dbschema -d logix -t movto_ega_drummer movto_ega_drummer.sql
dbschema -d logix -t proc_apont_man912 proc_apont_man912.sql
dbschema -d logix -t arranjo_drummer arranjo_drummer.sql
dbschema -d logix -t operad_pad_man912  operad_pad_man912.sql
dbschema -d logix -t par_rejei_454 par_rejei_454.sql
dbschema -d logix -t par_ega_logix_912 par_ega_logix_912.sql
dbschema -d logix -t man_ordem_drummer man_ordem_drummer.sql
dbschema -d logix -t man_oper_drummer man_oper_drummer.sql
dbschema -d logix -t man_necd_drummer man_necd_drummer.sql
dbschema -d logix -t par_ajust_454 par_ajust_454.sql
dbschema -d lan_cont_polimetri lan_cont_polimetri.sql
