
CREATE TABLE informix.obf_config_fiscal ( 
    empresa                    	CHAR(2) NOT NULL,
    trans_config               	SERIAL NOT NULL,
    origem                     	CHAR(1) NOT NULL,
    tributo_benef              	CHAR(20) NOT NULL,
    formula                    	CHAR(20) NOT NULL,
    nat_oper_grp_desp          	INTEGER,
    grp_fiscal_regiao          	CHAR(10),
    estado                     	CHAR(2),
    municipio                  	CHAR(5),
    carteira                   	CHAR(2),
    finalidade                 	SMALLINT,
    familia_item               	CHAR(3),
    grupo_estoque              	SMALLINT,
    grp_fiscal_classif         	CHAR(10),
    classif_fisc               	CHAR(10),
    linha_produto              	SMALLINT,
    linha_receita              	SMALLINT,
    segmto_mercado             	SMALLINT,
    classe_uso                 	SMALLINT,
    unid_medida                	CHAR(3),
    produto_bonific            	CHAR(1),
    grupo_fiscal_item          	CHAR(10),
    item                       	CHAR(15),
    micro_empresa              	CHAR(1),
    grp_fiscal_cliente         	CHAR(10),
    cliente                    	CHAR(15),
    via_transporte             	SMALLINT,
    acresc_desc                	CHAR(1) NOT NULL,
    aplicacao_val              	CHAR(1),
    tip_acresc_desc            	CHAR(2),
    aliquota                   	DECIMAL(7,4),
    val_unit                   	DECIMAL(17,6),
    pct_aplicacao_base         	DECIMAL(7,4),
    pre_uni_mercadoria         	DECIMAL(17,4),
    pct_acre_bas_calc          	DECIMAL(7,4),
    pct_red_bas_calc           	DECIMAL(7,4),
    pct_diferido_base          	DECIMAL(7,4),
    pct_diferido_val           	DECIMAL(7,4),
    pct_acresc_val             	DECIMAL(7,4),
    pct_reducao_val            	DECIMAL(7,4),
    pct_margem_lucro           	DECIMAL(7,4),
    pct_acre_marg_lucr         	DECIMAL(7,4),
    pct_red_marg_lucro         	DECIMAL(7,4),
    taxa_reducao_pct           	DECIMAL(7,4),
    taxa_acresc_pct            	DECIMAL(7,4),
    incide                     	CHAR(1),
    zerar_bas_calc             	CHAR(1),
    origem_produto             	SMALLINT,
    tributacao                 	SMALLINT,
    hist_fiscal                	INTEGER,
    lista_preco                	CHAR(8),
    base_pauta                 	DECIMAL(17,6),
    val_unit_minimo            	DECIMAL(17,6),
    val_trib_benef_min         	DECIMAL(17,6),
    tip_retencao               	CHAR(1),
    sit_tributo                	CHAR(1),
    retido_devido              	CHAR(1),
    motivo_retencao            	CHAR(1),
    retencao_cre_vdp           	CHAR(3),
    cod_fiscal                 	INTEGER,
    docum_refer                	CHAR(1),
    moed_corrc_monet           	SMALLINT,
    inscricao_estadual         	CHAR(16),
    dipam_b                    	CHAR(3),
    pre_list_x_nf              	CHAR(1),
    valid_config_ini           	DATE,
    valid_config_final         	DATE,
    aliq_icms_normal           	DECIMAL(7,4),
    pct_desc_icms_nrml         	DECIMAL(7,4),
    retir_ipi_bc_icms          	CHAR(1),
    marg_x_lista_preco         	CHAR(1),
    cod_servico                	CHAR(15),
    estado_gnre                	CHAR(5),
    receita_gnre               	CHAR(10),
    num_convenio_gnre          	CHAR(55),
    texto_gnre                 	INTEGER,
    matriz                     	CHAR(40),
    cotacao_moeda_upf          	DECIMAL(7,2),
    simples_nacional           	DECIMAL(5,0),
    gera_duplicata_gnre        	CHAR(1),
    iden_processo              	INTEGER,
    contrato_gco               	CHAR(16),
    aliq_carga_tributaria_media	DECIMAL(7,4),
    aliquota_frete_autonomo    	DECIMAL(7,4),
    motivo_desoneracao         	CHAR(2),
    exige_codif                	CHAR(1),
    aliq_icms_cst_60           	DECIMAL(7,4),
    ft_cnv_qtd_bc              	DECIMAL(11,6),
    aliq_icms_st_fem           	DECIMAL(7,4),
    PRIMARY KEY(empresa,trans_config)
	ENABLED
)
LOCK MODE ROW
GO
