drop TABLE loc_entrega_885;
CREATE TABLE loc_entrega_885(
	numsequencia int ,
	codcliente char(15) ,
	razaosocial char(99) ,
	nrloja char(15) ,
	nrlocalentrega char(15) ,
	numcnpj char(19) ,
	inscestatual char(16) ,
	email char(50) ,
	endereco char(120) ,
	bairro char(40) ,
	cep char(9) ,
	telefone1 char(20) ,
	telefone2 char(20) ,
	municipio char(50) ,
	uf char(2) ,
	codcidade char(5) ,
	distancia int ,
	tempoviagem int ,
	tiporegistro char(1) ,
	statusregistro char(1) ,
	datatualizacao datetime ,
	nomprograma char(8) 
);
