SELECT PARAMETRO[94,100] FROM PAR_CRE_TXT
select * from adocum_pgto_capa WHERE COD_EMPRESA= '02' AND NUM_LOTE >= 103794
SELECT * FROM PGTO_CAPA WHERE COD_EMPRESA= '02' AND NUM_LOTE >= 103794
SELECT * FROM PGTO_DET WHERE COD_EMPRESA= '02' AND NUM_LOTE >= 103794
SELECT * FROM DOCUM_PGTO WHERE  NUM_DOCUM = '01049963-01' AND COD_EMPRESA='02'  AND IES_TIP_DOCUM='DP'
SELECT * FROM DOCUM WHERE  NUM_DOCUM = '01049963-01' AND COD_EMPRESA='02'  AND IES_TIP_DOCUM='DP'

SELECT * FROM FORMA_PGTO WHERE COD_FORMA_PGTO = 'BC'
SELECT MAX(NUM_SEQ) FROM PGTO_DET WHERE COD_EMPRESA= '02' AND NUM_LOTE= 103789   AND COD_PORTADOR= 237 AND IES_TIP_PORTADOR= 'B'
SELECT COUNT (*) FROM PAR_TIPO_DOCUM WHERE COD_EMPRESA = '02' AND IES_TIP_DOCUM = 'DP' HAVING COUNT (*)>0
SELECT IES_TIP_COBR,* FROM DOCUM WHERE COD_EMPRESA = '02'  AND IES_TIP_DOCUM = 'DP' AND IES_PGTO_DOCUM != 'T'
   AND IES_SITUA_DOCUM != 'C'
SELECT * FROM PGTO_DET WHERE COD_EMPRESA='02' AND NUM_LOTE=103794 AND COD_PORTADOR=237 AND IES_TIP_PORTADOR='B'
   AND EMPRESA_DOCUM='02' AND NUM_DOCUM='05007022-01' AND IES_TIP_DOCUM='DP'
SELECT PAR_IES FROM PAR_CHE_PAD WHERE COD_PARAMETRO='ies_ctr_cheque' AND COD_EMPRESA='01'
SELECT MAX(NUM_SEQ_DOCUM) FROM DOCUM_PGTO WHERE COD_EMPRESA='02' AND NUM_DOCUM='05007022-01' AND IES_TIP_DOCUM='DP'
SELECT * FROM DOCUM_PGTO WHERE  NUM_DOCUM='92489' AND COD_EMPRESA='02'  AND IES_TIP_DOCUM='DP'
SELECT * FROM DOCUM WHERE  NUM_DOCUM='92489' AND COD_EMPRESA='02'  AND IES_TIP_DOCUM='DP'

select * from pgto_det where cod_empresa = '01'