
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','NAT_OPER_NF_PRODUT','NAT OPERACAO NF DE PRODUTOS','I')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','NAT_OPER_NF_SERVICO','NARUREZA DE OPERACAO P/ NF DE SERVICO','I')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','MODELO_DA_NF','MODELO DA NOTA FISCAL','C')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','ORIGEM_DA_NF','ORIGEM DA NOTA FISCAL','C')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','FINALIDADE_DA_NF','FINALIDADE DA NOTA FISCAL','C')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','COD_DA_CARTEIRA','CODIGO DA CARTEIRA','C')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','COD_REPRESENTANTE','CODIGO DO REPRESENTANTE','I')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','COD_COND_PGTO','CODIGO DA COND PAGAMENTO','I')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','COD_TIP_CLIENTE','CODIGO DO TIPO DE CLIENTE','C')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','COD_CLASSE_CLIENTE','CODIGO DA CLASSE DO CLIENTE','C')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','SUB_SER_NF_SERVICO','SUB SERIE DA NF DE SERVICO','I')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','SUB_SER_NF_ENTRADA','SUB SERIE DA NF DE ENTRADA','I')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','COD_TIP_FRETE','CODIGO DO TIPO DE FRETE','C')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','SUB_SER_NF_DEVOLUCAO','SUB SERIE DA NF DE DEVOLUCAO','I')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','COD_MOD_EMBARQUE','CODIGO DO MODO DE EMBARQUE','I')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','COD_OPER_NF_ENTRADA','CODIGO OPERACAO NF ENTRADA','C')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','CFOP_NF_SERVICO','CFOP DA NOTA DE SERVICO','C')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','COD_DESC_INCOND','CODIGO DO DESCONTO INCONDICIONAL','C')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','COD_DESC_CENP','CODDIGO DO DESCONTO CENP','C')
 insert into par_omc_509(cod_empresa,cod_parametro,den_parametro,par_tipo) values('01','COD_UNID_MEDIDA','CODIGO DA UNIDADE DE MEDIDA','C')
