<?php
          printf("<td width='50'  style=$n_style colspan='5'     align='center'>
          <input type='hidden' name='ifx_user' value='".$usuario."' size='10' maxlenght='10'> 
          </td>
          <td width='50'  style=$n_style colspan='5'     align='center'>
          <input type='hidden' name='progc' value='".$prog."' size='10' maxlenght='10'> 
          </td>
         <td width='50'  style=$n_style colspan='5'     align='center'>
         <input type='hidden' name='ifx_senha' value='".$senha."' size='10' maxlenght='10'> 
         </td>");
?>
