<?php
         printf("<tr>
                 <td width='150'  style=$n_style colspan='15'     align='left'>
          <i><font face='Arial, Helvetica, sans-serif' size='3' color=$c_color>
          Codigo Cliente:</font></i>
          </td>
          <td width='50'  style=$n_style colspan='5'     align='center'>
          <input type='text' name='cod_cliente' size='10' maxlenght='10'> 
          </td>");
?>
