<?php
         printf("<td width='350'  style=$n_style colspan='35'     align='right'>
          <i><font face='Arial, Helvetica, sans-serif' size='3' color=$c_color>
          Informe qualquer parte do nome Fornecedor:</font></i>
          </td>
          <td width='150'  style=$n_style colspan='15'     align='left'>
          <input type='text' name='nom_' size='50' maxlenght='100'> 
          </td></tr><tr>");

         printf("<td width='350'  style=$n_style colspan='35'     align='right'>
          <i><font face='Arial, Helvetica, sans-serif' size='3' color=$c_color>
          Ou CGC/CPF Conforme cadastro Logix:</font></i>
          </td>
          <td width='50'  style=$n_style colspan='5'     align='letf'>
          <input type='text' name='cgc_' size='15' maxlenght='15'> 
          </td>");

?>
