<?php
  $nome_=$mensagem1;
  include("../../bibliotecas/style.inc");
  printf("<html>");
  printf("<head>");
  printf("<meta http-equiv='Content-Type' content='text/html;charset=iso-8859-1'>");
  printf("<title>'ACESSO NÃO AUTORIZADO'</title>");
  printf("</head>");
     printf(" 
             <tr>
               <td width='750'  style=$n_style  COLSPAN=75    align='center'>
                <i><font face='Arial, Helvetica, sans-serif' size='5' color=red>
                 </font></i>
               </td>
             </tr>
             <tr>
               <td width='750'  style=$n_style  COLSPAN=75    align='center'>
                <i><font face='Arial, Helvetica, sans-serif' size='5' color=red>
                 </font></i>
               </td>
             </tr>
              <tr>
               <td width='750'  style=$n_style COLSPAN=75     align='center'>
                <i><font face='Arial, Helvetica, sans-serif' size='5' color=red>
                $mensagem1 </font></i>
              </td>
             </tr>
             <tr>
               <td width='750'  style=$n_style  COLSPAN=75    align='center'>
                <i><font face='Arial, Helvetica, sans-serif' size='5' color=red>
                 </font></i>
               </td>
             </tr>
             <tr>
               <td width='750'  style=$n_style  COLSPAN=75    align='center'>
                <i><font face='Arial, Helvetica, sans-serif' size='5' color=red>
                 </font></i>
               </td>
             </tr>

             <tr>
               <td width='750'  style=$n_style  COLSPAN=75    align='center'>
                <i><font face='Arial, Helvetica, sans-serif' size='5' color=red>
                $mensagem2</font></i>
               </td>
             <tr>
             <tr>
               <td width='750'  style=$n_style  COLSPAN=75    align='center'>
                <i><font face='Arial, Helvetica, sans-serif' size='5' color=red>
                 </font></i>
               </td>
             </tr>
               <td width='750'  style=$n_style  COLSPAN=75    align='center'>
                <i><font face='Arial, Helvetica, sans-serif' size='5' color=red>
                $mensagem3</font></i>
               </td>

      </table>         
     </FORM>
     </tr>");
?> 
