<?php
$dia=date("d");
$mes=date("m");
$ano=date("Y");
$c_color="#000099";
$data=sprintf("%02d/%02d/%04d",$dia,$mes,$ano);
         printf("<TABLE WIDTH=750 BORDER=0 border-style=solid bordercolor='#3366cc'  CELLPADDING=1 CELLSPACING=0 RULES=groups  style='page-break-after:right' >
         <tr >
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         </tr>
         <tr>
         <td width='300' style=$n_style rowspan='3' colspan='30'  ><img src='../../imagens/logocpd3.jpg'></td> 
         <td width='450'  style=$n_style colspan='45'     align='left'>
         <b><font face='Arial, Helvetica, sans-serif' size='2'color=$c_color>
         $nome_</font></b>
         </td>
         </tr>
         <tr>
         <td width='380'  style=$n_style colspan='38'     align='right'>
         <b><i><font face='Arial, Helvetica, sans-serif' size='2' color=$c_color>
         Data:</font></i></b>
         </td>
         <td width='70'  style=$n_style colspan='7'     align='left'>
         <b><i><font face='Arial, Helvetica, sans-serif' size='2' color=$c_color>
         $data</font></i></b>
         </td>
         </tr>
         </tr>
         <tr>
         </tr>
         </table>
         <TABLE WIDTH=750 BORDER=0 border-style=solid bordercolor=$c_color  CELLPADDING=1 CELLSPACING=0 RULES=groups  style='page-break-after:right' >
         <tr >
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         <td width='10' style=$n_style height=1 ></td>
         </tr>
");

?>
