CREATE TABLE nf_item_792G (
			cod_empresa				CHAR(02),
			num_docum					DECIMAL(6,0),
			especie						CHAR(03),
			cod_cliente 			CHAR(14),
			sequencia					DECIMAL(5,0),
			cod_item 					CHAR(15) ,
			den_item					CHAR(76),
			qtd_item					DECIMAL(17,6),
			unidade_medida		CHAR(3),
			pre_unit					DECIMAL(17,6),
			val_liq_item			DECIMAL(17,6),
			pct_icms					DECIMAL(5,2),
			val_tot_base_icms	DECIMAL(17,2),
			val_tot_icms			DECIMAL(17,2),
			pct_irpj					DECIMAL(5,2),
			val_base_irpj			DECIMAL(15,2),
			val_irpj					DECIMAL(15,2),
			pct_csll					DECIMAL(5,2),
			val_base_csll			DECIMAL(15,2),
			val_csll					DECIMAL(15,2),
			pct_cofins				DECIMAL(5,2),
			val_base_cofins		DECIMAL(15,2),
			val_cofins				DECIMAL(15,2),
			pct_pis						DECIMAL(5,2),	
			val_base_pis			DECIMAL(15,2),
			val_pis						DECIMAL(5,2)
);	
